### PR TITLE
Fix broken image links in mail notificaitons

### LINKED ISSUE #4: [P1] Mail notifications images links are broken
All the images in the Job Match Mail notification point to urls that are broken -
screen shot 2015-09-06 at 11 52 52 am

### PR DESCRIPTION
**Pull request by codelion**
This fixes #4

### CODE REVIEW

**Comment by codelion** [comment]
Just realized that the image used as logo in the mail notification is not a transparent png so it shows up with white background - 

screen shot 2015-09-06 at 12 21 38 pm

Hold off reviewing, let me fix that in this PR as well.

**Comment by ghost** [comment]
@codelion i had removed the intajobs.com link, don't know from where it came. also the png was fixed earlier.

**Comment by ghost** [comment]
you have to add this to file, image is already hosted
http://instajobs.io/assets/images/logo-only-sm.png

**Comment by codelion** [comment]
@avidyut1, that file also has the white background just that the size is smaller.

**Comment by codelion** [comment]
Found the problem, it is due to the element style having its background color set to white.

**Comment by codelion** [comment]
Ready for PR :8ball:

**Comment by codelion** [comment]
This is how it looks now - 
screen shot 2015-09-06 at 1 54 09 pm

**Pull request merged**
